project:
  type: website
  output-dir: docs

website:
  title: "SPARTA — Spatial Reasoning and Therapeutics with AI : From Omics to Imaging"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/spartaaaai2026-workshop/SPARTA_AAAI_workshop_2026
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Call for poster presentations
      - href: organizers.qmd
        text: Orgnaizers
      - href: https://github.com/spartaaaai2026-workshop/SPARTA_AAAI_workshop_2026/discussions
        text: Forum

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

